### ISSUE TITLE
Correctly handle OS shutdown

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#13]
OS shutdown must be correctly handled by the script. Right now script interrupt when openvnp closed as requested by OS, then (as I can understand) script restart openvpn, but it must END his job too.

Need to add `SIGTERM` handler. I'm not sure how to do this, but maybe to add at the start of the program something like this: 

`def sigterm_handler(_signo, _stack_frame):
    # close open vpn instances if they are connected.
    sys.exit(0)

signal.signal(signal.SIGTERM, sigterm_handler)
signal.signal(signal.SIGKILL, sigterm_handler)`

p.s. and SIGKILL

**Comment by Dragon2fly** [comment]
Sending SIGTERM to `openvpn` process, such as `sudo kill #pid`, did terminate the vpn connection and the script didn't restart openvpn.

Did you mean that sending SIGTERM to the script didn't work properly? Right now the script itself is not handle SIGTERM and so doesn't do the `post_action`.

**Comment by evadogstar** [comment]
@Dragon2fly First reboot after update: works ok! But need more testing :) thanks for this update.
p.s. Configs now have other permissions to keep them on updates?

**Comment by Dragon2fly** [comment]
uhm, the line before that line should already check if the file exist or not. 
`config.ini` and `user_script.sh` have the same processing code. If the is a problem, then it should happen to the `config.ini` first as it is processed before `user_script.sh`.

Can you confirm this error again?

**Comment by evadogstar** [comment]
I think this error related to this issue: https://github.com/Dragon2fly/vpngate-with-proxy/issues/14#issuecomment-298898482 
It was a problem with writing configs to `/root`. 

While we have open issue linked above and this ticket about SIGTERM solved: I do not expect now any problems with shutdown. This ticket can be closed. Thanks

**Comment by Dragon2fly** [comment]
Can you do one more test below before I close this issue?

open the `vpnproxy_cli.py` file and put this line 

    print os.path.realpath("user_script.sh")

before this line

    if not os.path.exists("user_script.sh"):

to see if the printed path is the expected one.

**Comment by evadogstar** [comment]
It show: 
/home/user/vpngate-with-proxy/user_script.sh

Note:
 - it's cli file of previous version.
 - Before that to fix issue with `/root` folder I delete user_script.sh at `vpngate_with_proxy` dir and put my `user_script.sh`

I will test the same with current version
-------------
On recent clean version: 
1) First of all it give this error https://i.imgur.com/mbgJluf.png

**Comment by Dragon2fly** [comment]
I found an error! It's my bad leaving the `expanduser('~')` code intact. I replaced it with proper `user_home`. Now it should be fine on your system. Please confirm with the newest push

**Comment by evadogstar** [comment]
I delete folder at `.config` dir and clone new repository. Now, it's executed without error. Thanks. :)
