### ISSUE TITLE
Issue with configs not at user folder

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#14]
Unfortunately, configs stored at root folder, because of sudo :( , but **expected** to find them at user folder with user permissions :( I was confused, before I look at the code and found that `~/` will be `root` home :)

At user folder who call `./run` script. I think the most correct way will be to get user at `./run` with `USER=$(whoami)` then transfer it to python vpn_gate_script as an variable (or maybe better to get $USERFOLDER at run script and transfer it. Then change `~/` to `$USERFOLDER`

p.s. But root folder at my OS always clean after each reboot and I loose `user_script.sh` and `config` :( It's really better to score configs at user folder who call the script as all programs do :)

Sorry, it was my suggestion about storing configs at user home and this add a lot of unexpected work :(

**Comment by Dragon2fly** [comment]
uhm, that is a weird behaviour. On my ubuntu, `~` is expanded into `user`'s home folder even if it is called with `sudo`. It should only point to `\root` when you are already in root privilege, not by temporarily elevating into root with `sudo`.

Could you check the output of these commands:

- elevating privilege temporarily: `sudo echo $HOME`
- already in root: `sudo su` then `echo $HOME`

They should not return the same result.

**Comment by evadogstar** [comment]
`sudo echo $HOME` give me correct `user` home, not root home. But look into this, please: 
https://i.imgur.com/YOajmGA.png
Is it correct that `config.ini` and `user_script.sh` linked to `/root/`? Not root home, but `/root/`

There is one other tricky thing that I do every time after I download new version and **maybe** this give such result. I edit `run` script from `python vpnproxy_cli.py $arg`  to  `sudo sg qvpn -c "python vpnproxy_cli.py $arg"`(Because network access available only for qvpn group on the system.

**Comment by Dragon2fly** [comment]
what is the output of `sudo sg qvpn -c "echo $HOME"`? is it `/root`?

**Comment by evadogstar** [comment]
>> `sudo sg qvpn -c "echo $HOME"`
return: `/home/user/` ... 

>> update
Thanks, I will try. 
It's a pity that it does not detect it as `/home/user/`

**Comment by Dragon2fly** [comment]
> sudo sg qvpn -c "echo $HOME"
> return: /home/user/ 
Then I don't know how and where `\root` comes from :( 
Hope the update helps you bypass this problem.

**Comment by Dragon2fly** [comment]
Since your problem solved. I close this too
