### ISSUE TITLE
ConfigParser.py error

### ISSUE THREAD

**Issue by msalini** [Dragon2fly/vpngate-with-proxy#20]
After changing the DNS values (successfully) and initiated connection, I get this error.
(see image)

https://anonimage.net/image/oEirzH1BUu

I should add that this error does not occur when I keep the default DNS list.
Please advise

Thanks

Marco

**Comment by Dragon2fly** [comment]
That's the bug. 
The inputted DNS value is for write out to file so it should not be converted from string to list.

You could either edit the `config.ini` file and put `dns = 91.239.100.100, 89.233.43.71` into it or delete it and clone this project again.

**Comment by msalini** [comment]
Thank you D2f,

fixed as you suggested :-)

Marco
