### ISSUE TITLE
How to access local domain with VPN?

### ISSUE THREAD

**Issue by lbngoc** [Dragon2fly/vpngate-with-proxy#22]
Currently, I use dnsmasq to forward all domain with TLD .dev to my local ip 127.0.0.1, everything is working fine. But when I connect to a VPN, I cannot open my domain.dev, please help me to config it.

**Comment by Dragon2fly** [comment]
Hi @lbngoc 

The program changes your DNS to Google while you are on VPN to prevent DNS leak. If you already have the your DNS working securely, then you just need to disable `Fix DNS Leak` option in order to use your own DNS server. 

Happy new year.
