### ISSUE TITLE
Indicator not show in gnome

### ISSUE THREAD

**Issue by sonvirgo** [Dragon2fly/vpngate-with-proxy#23]
I run vpn_indicator.py in background, so there is a notify at gnome top bar when the vpn connected.
But I dont see this ![Image of Yaktocat](https://camo.githubusercontent.com/6bce8eca18c98a39db8d2a547d5d9e0b8ddd2d3a/68747470733a2f2f7331392e706f7374696d672e6f72672f356c373771327138332f38696e64696361746f722e706e67)

**Comment by Dragon2fly** [comment]
Hi @sonvirgo ,

Which OS are you using?
Did you install the required packet yet?

    sudo apt-get install gir1.2-appindicator3-0.1 gir1.2-notify-0.7 python-gobject

**Comment by sonvirgo** [comment]
Hi @Dragon2fly ,
I am running Ubuntu 17.04, Gnome 3.24
All required packages are already installed
Also, the F4 filter for country not work, the server for specific country seen in the list but filter always return empty result for any country
And the app blocking the console hence Gnome-shell freeze upon connected to a slow server.

**Comment by sonvirgo** [comment]
Update
this is the error 
`(vpn_indicator.py:12272): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`
sorry, the freeze issue is cause by other app:  autovpn extenssion

**Comment by Dragon2fly** [comment]
Hi @sonvirgo , 

Is your problem solved?

**Comment by sonvirgo** [comment]
Hi @Dragon2fly,
Indicator not show yet
Country filter not work too

**Comment by Dragon2fly** [comment]
Hi @sonvirgo ,

I've just tested it on a fresh Ubuntu Gnome 17.04.

Indicator is shown at the bottom left of the screen.
Country filter works fine with lower case input. So don't use UPPER case with the filter.

One problem though,  `ifconfig` is not there anymore. 
What did you do to solve it?
