### ISSUE TITLE
Show connection information

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#3]
After connection done user see "Changed DNS" and "VPN tunnel established".
I suggest to add a lot of more information: Country connected to, IP. It's already available at the top, but need to scroll. But not a big problem :)

**Comment by Dragon2fly** [comment]
Well, `tui` version already show a bunch of information related to the VPN tunnel. The aim of `cli` is light and fast. :)

**Comment by evadogstar** [comment]
No problem if it will be as it is already at `cli`
