### ISSUE TITLE
[feedback] Python3 thanks. It works

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#31]
Hello,  Thank you! 

Previous python2 version worked up for many-many years ( 4 years, wow!) to the present moment before fedora 32 drop python2 support. As soon as I found that it no longer works.... I begin thinking about inventing bicycle, but thank you again I visit your repo and found new python3 version based on previous release and it's works fine after some minor changes for my system :-) 

p.s. I run it not as root, but as other user to prevent leaks, because of this I change "run" file each time + user_script.sh

 :+1:

**Comment by evadogstar** [comment]
works on fedora 32 btw

**Comment by Dragon2fly** [comment]
I'm glad that it has helped you for so long. 😃
