### ISSUE TITLE
Network and Proxy Problem

### ISSUE THREAD

**Issue by ambvalent** [Dragon2fly/vpngate-with-proxy#34]
Hi, I encountered an error. I do the guide and troubleshooting but still got this error.

![image](https://user-images.githubusercontent.com/80581586/146661457-fb498bde-1528-43ee-a9e9-d3d11f65c893.png)

**Comment by Dragon2fly** [comment]
Hi, can you show the proxy that you are using?
The log tells that something is wrong with the proxy string.

**Comment by maryhele** [comment]
Hi, this is the proxy that I'm using my.http.proxy 

![image](https://user-images.githubusercontent.com/75470296/147509478-d07cf53c-602c-4b76-8747-3ad5e23b59da.png)

**Comment by Dragon2fly** [comment]
hi @maryhele,

You need to replace `my.http.proxy` with your real proxy address!

But first, make sure that you can answer the following question: 
Is your network behind a proxy? or do you need the proxy to connect to the Internet?

If the answer is no, please set `3. Use proxy` to `no`

**Comment by ambvalent** [comment]
Hi,

It is working now. Thank you and Happy New Year :)
