### ISSUE TITLE
Fix vpn_indicator' vpn status "Season:" -> "Session:"

### ISSUE THREAD

**Issue by gsool9988** [Dragon2fly/vpngate-with-proxy#37]
After starting vpngate, **vpn_indicator** informs the status of the vpn connected. But a misspelling has catched my eyes. It is "Season:" maybe for "Session:"
To fix it, at first terminate vpn-gate, and open & edit indicator_config file, **~/vpngate-with-proxy/vpn_indicator.py**. 
Substitute **"Season:" -> "Session:"**
That's it :)

![Season_before_edit_file](https://user-images.githubusercontent.com/101626854/194245659-e60a4f29-ed1d-4d08-b809-420e30b0233a.png)

![Session_after_edit_file](https://user-images.githubusercontent.com/101626854/194245692-995ee6fe-f1fe-4adb-beb0-c90a1e070cad.png)

![vpn_status_2022-10-06 16-03-33](https://user-images.githubusercontent.com/101626854/194247613-82e2e514-02f4-4fc7-baeb-5d6d09df4cc1.png)

**Comment by Dragon2fly** [comment]
Thank you for your finding. I fixed the typo.

**Comment by gsool9988** [comment]
You're welcome. It's me to say that thank you very much. vpngate is one of
the best favorite apps in ubuntu for me. Thank you:)

2022년 10월 7일 (금) 오전 10:11, Dragon2fly ***@***.***>님이 작성:
