### ISSUE TITLE
Error on Run

### ISSUE THREAD

**Issue by masgandhul** [Dragon2fly/vpngate-with-proxy#6]
I'm doing neither ./run [arg] nor ./vpnproxy_tui.py and ./vpnproxy_cli.py has error. Thank you

```
File "vpnproxy_cli.py", line 95
    print ctext('Warning: ', 'yB'),
              ^
SyntaxError: invalid syntax
```
----
```
File "vpnproxy_tui.py", line 167
    print '\n' + '_' * 12 + ctext(' First time config ', 'gB') + '_' * 12 + '\n'
             ^
SyntaxError: invalid syntax
```

**Comment by Dragon2fly** [comment]
The default `python` on your machine is version 3. You can check it by `$ python -V` in terminal. The program requires python 2.7.x to run. 

Which OS are you using?

Try `$ python2 -V` to see if it is available. If not, `sudo apt-get install python2.7`

Then open the `run` file, replace `python` by `python2.7`, save it.

It should work fine then.
