### ISSUE TITLE
Notify version check issue

### ISSUE THREAD

**Issue by beng7** [Dragon2fly/vpngate-with-proxy#8]
Hi Dragon2fly,
First let me tell you I love this handy tool!
Also really waiting for the implementation of softether for it!

Anyway at the moment I am running into a little issue:

```bash
user@acer:~/vpngate-with-proxy$ `./run tui`
Traceback (most recent call last):
  File "vpnproxy_tui.py", line 21, in <module>
    from vpn_indicator import InfoClient
  File "/home/user/vpngate-with-proxy/vpn_indicator.py", line 22, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
user@acer:~/vpngate-with-proxy$ 
```

and here is the line in question; I commented it as a quick workaround but can you suggest anything better?
`#gi.require_version('Notify', '0.7')`

then I can `./run tui`, but after the initial configuration I click Enter, an rerun it, I get

```
`Lack of Gtk related modules! VPN indicator will not run!
 You should try "sudo apt-get install gir1.2-appindicator3-0.1 python-gobject`
```
althought these dependencies are met!

(my distro = [BunsenLab](https://www.bunsenlabs.org/), latest version, always kept up to date; it is based on Debian Jessie
Thanks a lot

**Comment by Dragon2fly** [comment]
Thanks for using my program.

To solve the problem, you need to install `gir1.2-notify-0.7`, too.  This makes the main program run but not the indicator. For the indicator, you need to modify the `run` file. On line 20, change `target='buntu'` to `target='debian'`.

Thanks for this issue, I do a little test on Bunsen and discover a bug of detecting package manager. Now it is fixed too. :)

**Comment by beng7** [comment]
Hey Dragon2fly,
Thanks a lot for the customized support ;)
Will do as you instruct.
Well of you need a beta tester for Bunsen Lab you can ask me.
Will get back to you to let you know if sorted.
Thanks again

On 14 February 2017 08:38:01 CET, Dragon2fly <notifications@github.com> wrote:
>Thanks for using my program.
>
>To solve the problem, you need to install `gir1.2-notify-0.7`, too. 
>This makes the main program run but not the indicator. For the
>indicator, you need to modify the `run` file. On line 20, change
>`target='buntu'` to `target='debian'`.
>
>Thanks for this issue, I do a little test on Bunsen and discover a bug
>of detecting package manager. Now it is fixed too. :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dragon2fly/vpngate-with-proxy/issues/8#issuecomment-279629957

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by beng7** [comment]
Hi again
did modifications as instructed, better already - I have the notifier
yet
`user@acer:~$ cd vpngate-with-proxy
user@acer:~/vpngate-with-proxy$ ./run tui

**Lack of dependencies**

Have you 'sudo apt-get update' recently?([yes] | no): yes

___Now installing python-pip

Traceback (most recent call last):
  File "vpnproxy_tui.py", line 1035, in <module>
    call([pkg_mgr, '-y', 'install', package], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
installed python-pit properly and it looks like I'm finally running

Thank YOU!
looking forward to softether implementation
cheers

**Comment by Dragon2fly** [comment]
> OSError: [Errno 2] No such file or directory

As said above, this problem due to the mis-detection of package manager on Bunsen. The program thought Busen is Redhat based os, so it tried to use `yum/dnf` instead of `apt-get`. Of course their is no `yum` on the system as the error said.

I've already pushed the fix for this. If you clone again, you won't see this problem. 

> No objections to editing the list of dns servers in the config.ini/F3?

Not, at all. If you edit the file, just make sure the program is not running.
